name: CI build to verify quality
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  verify-quality:
    name: Verify quality
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Verify quality
        run: dotnet test --solution Eshva.Caching.Nats.slnx --retry-failed-tests 5 --report-xunit --report-xunit-filename test_result.xml --results-directory .
        working-directory: ./code
      - name: Publish test results
        if: (!cancelled())
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "./**/test_result.xml"
          check_name: "Test results"
          action_fail: true
